// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bS_QkOtwFdspxq3IlyTSCPJll3hGEy8',
    appId: '1:398276701103:web:8d79a49e01203c95d71d5a',
    messagingSenderId: '398276701103',
    projectId: 'pokerspot',
    authDomain: 'pokerspot.firebaseapp.com',
    storageBucket: 'pokerspot.firebasestorage.app',
    measurementId: 'G-6JYP2GGN56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuS6KdgP9q2AeDQp7YLwBoKHsqtRde3R4',
    appId: '1:398276701103:android:8fcb991bed19ffaed71d5a',
    messagingSenderId: '398276701103',
    projectId: 'pokerspot',
    storageBucket: 'pokerspot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vlaOyMCPles1xduM0LtbU5dG5nCWQ5E',
    appId: '1:398276701103:ios:ad8b6be26141e247d71d5a',
    messagingSenderId: '398276701103',
    projectId: 'pokerspot',
    storageBucket: 'pokerspot.firebasestorage.app',
    iosBundleId: 'com.pokerspot.pokerspot',
  );
}
